name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: | # The "|" is a YAML multiline string operator that lets you write multiple commands across several lines
        pip install uv
        uv sync
    
    - name: Run Python script
      run: uv run python main.py